version: '3.8'

services:
  database:
    image: mariadb:latest
    container_name: board-game-db
    environment:
      MYSQL_ROOT_PASSWORD: securepassword
      MYSQL_DATABASE: BoardGameDirectory
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - board-game-network
    ports:
      - "3306:3306"

  app:
    build:
      context: .
    container_name: board-game-app
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: securepassword
      DB_NAME: BoardGameDirectory
      DB_PORT: 3306
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 3000
    networks:
      - board-game-network
    ports:
      - "3000:3000"
    depends_on:
      - database

  test:
    build:
      context: .
    container_name: board-game-test
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: securepassword
      DB_NAME: BoardGameDirectory
      DB_PORT: 3306
    depends_on:
      - database
    networks:
      - board-game-network
    command: npm test

networks:
  board-game-network:
    driver: bridge
