-- Active: 1734932060270@@127.0.0.1@3306
CREATE DATABASE IF NOT EXISTS miedev;

USE miedev;

DROP TABLE IF EXISTS FAVORITES;
DROP TABLE IF EXISTS SCORES;
DROP TABLE IF EXISTS EVENTS;
DROP TABLE IF EXISTS SESSIONS;
DROP TABLE IF EXISTS GAMES;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE GAMES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL UNIQUE,
    DESCRIPTION TEXT DEFAULT NULL,
    CATEGORY VARCHAR(100) DEFAULT NULL,
    MIN_PLAYERS INT DEFAULT NULL,
    MAX_PLAYERS INT DEFAULT NULL,
    PLAYTIME INT DEFAULT NULL,
    IMAGE_URL VARCHAR(255) DEFAULT NULL,
    OWNER_ID INT DEFAULT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (OWNER_ID) REFERENCES USERS(ID) ON DELETE SET NULL
);

CREATE TABLE SESSIONS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    GAME_ID INT NOT NULL,
    DATE_PLAYED DATE NOT NULL,
    NOTES TEXT DEFAULT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (GAME_ID) REFERENCES GAMES(ID) ON DELETE CASCADE
);

CREATE TABLE FAVORITES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    GAME_ID INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (GAME_ID) REFERENCES GAMES(ID) ON DELETE CASCADE,
    UNIQUE(USER_ID, GAME_ID)
);

CREATE TABLE SCORES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    SESSION_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    SCORE INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SESSION_ID) REFERENCES SESSIONS(ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

CREATE TABLE EVENTS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DATE DATE NOT NULL,
    LOCATION VARCHAR(255) NOT NULL,
    GAMES_TO_PLAY TEXT DEFAULT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO USERS (USERNAME, EMAIL) VALUES
('Vinay', 'vinay@email.com'),
('Vikram', 'vikram@email.com'),
('Hemanth', 'hemanth@email.com'),
('Riyaz', 'riyaz@email.com');

INSERT INTO GAMES (NAME, DESCRIPTION, CATEGORY, MIN_PLAYERS, MAX_PLAYERS, PLAYTIME, IMAGE_URL, OWNER_ID) VALUES
('Checkers', 'Classic strategy game for two players.', 'Strategy', 2, 2, 30, 'C:/Users/riyaz/OneDrive/Pictures/Screenshots 1/Screenshot 2024-12-23 001203.png', 1),
('Ludo', 'A fun family board game based on rolling dice.', 'Family', 2, 4, 60, 'C:/Users/riyaz/OneDrive/Pictures/Screenshots 1/Screenshot 2024-12-23 001400.png', 2),
('Snake & Ladders', 'A dice-based game of climbing and sliding.', 'Family', 2, 6, 45, 'C:/Users/riyaz/OneDrive/Pictures/Screenshots 1/Screenshot 2024-12-23 001532.png', 3),
('Monopoly', 'A real estate trading game.', 'Strategy', 2, 6, 180, 'C:/Users/riyaz/OneDrive/Pictures/Screenshots 1/Screenshot 2024-12-23 001644.png', 4),
('Scrabbles', 'A word game for creating words on a board.', 'Word', 2, 4, 90, 'C:/Users/riyaz/OneDrive/Pictures/Screenshots 1/Screenshot 2024-12-23 001818.png', 4);

INSERT INTO SESSIONS (GAME_ID, DATE_PLAYED, NOTES) VALUES
(1, '2024-12-01', 'Close match between players.'),
(2, '2024-12-05', 'Family fun night.'),
(3, '2024-12-07', 'Quick game to test skills.'),
(4, '2024-12-10', 'Longest Monopoly game yet.'),
(5, '2024-12-18', 'High-scoring Scrabble session.');

INSERT INTO FAVORITES (USER_ID, GAME_ID) VALUES
(1, 1),
(2, 2),
(3, 5),
(4, 4);

INSERT INTO SCORES (SESSION_ID, USER_ID, SCORE) VALUES
(1, 1, 50),
(1, 2, 45),
(2, 2, 100),
(3, 3, 90),
(4, 4, 300);

INSERT INTO EVENTS (NAME, DATE, LOCATION, GAMES_TO_PLAY) VALUES
('Family Game Night', '2024-12-25', 'Vinay\'s Residence', '2,3'),
('Strategy Sunday', '2024-12-29', 'Community Center', '1,4'),
('Scrabble Championship', '2025-01-02', 'Library Hall', '5');

SELECT G.ID, UPPER(G.NAME) AS NAME, UPPER(G.DESCRIPTION) AS DESCRIPTION, G.IMAGE_URL, MAX(S.DATE_PLAYED) AS LAST_PLAYED
FROM GAMES G
LEFT JOIN SESSIONS S ON G.ID = S.GAME_ID
GROUP BY G.ID, G.NAME, G.DESCRIPTION, G.IMAGE_URL;