name: Build and Test Dockerized App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build and Start Services
      - name: Build and Start Services
        run: |
          docker-compose up --build -d

      # Step 4: Run Tests
      - name: Run Tests
        run: |
          docker-compose up test
          docker logs board-game-test

      # Step 5: Stop Services
      - name: Stop Services
        run: |
          docker-compose down
