name: Build and Test Dockerized App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Step 4: Build and Start Services
      - name: Build and Start Services
        run: |
          docker-compose up --build -d

      # Step 5: Run Tests
      - name: Run Tests
        run: |
          docker-compose up test
          docker-compose logs test

      # Step 6: Stop Services
      - name: Stop Services
        run: |
          docker-compose down
